<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"/>
        <title>Verify Your Phone Number</title>

        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" media="screen, projection" />
    </head>
    <body>
        <div className="container">
            <div className="form-group">
                <div id="verify_phone_container"></div>
            </div>
        </div>

        <!-- Dependencies -->
        <script crossorigin src="https://unpkg.com/react@16/umd/react.development.js"></script>
        <script crossorigin src="https://unpkg.com/react-dom@16/umd/react-dom.development.js"></script>

        <!-- Main -->
        <script src="./dist/bundle.js"></script>
    </body>
</html>
